export const goalTypes = [
  {
    id: "63f4e94670f0c00c2f2b7386",
    label: "Build my credit score",
    altLabel: "Credit score improvement",
    activeTenseLabel: "building my credit score",
    icon: "💯",
    requiresCustomLabel: false,
  },
  {
    id: "63f5dfd1f16859cfec9f8b27",
    label: "Buy my new car",
    altLabel: "Shiny car purchase",
    activeTenseLabel: "buying my new wheels",
    icon: "🚗",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c43402170b8adfc12b",
    label: "Grow my savings",
    altLabel: "Savings plan",
    activeTenseLabel: "growing my savings",
    icon: "📈",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c43402170b8adfc135",
    label: "Get married",
    altLabel: "Wedding",
    activeTenseLabel: "getting hitched",
    icon: "💍",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c43402170b8adfc13f",
    label: "Go on holiday",
    altLabel: "Getaway plan",
    activeTenseLabel: "going on holiday",
    icon: "🏖️",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c43402170b8adfc149",
    label: "Move out",
    altLabel: "New crib",
    activeTenseLabel: "moving out",
    icon: "🏡",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c43402170b8adfc153",
    label: "Repay my loans faster",
    altLabel: "Get out of debt plan",
    activeTenseLabel: "repaying my loans faster",
    icon: "💳",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c53402170b8adfc15d",
    label: "Buy some shiny tech",
    altLabel: "Tech shopping spree",
    activeTenseLabel: "buying my new tech",
    icon: "💻",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c53402170b8adfc171",
    label: "Buy some drippy clothes",
    altLabel: "Shopping spree",
    activeTenseLabel: "buying some new threads",
    icon: "👖",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c53402170b8adfc17b",
    label: "Start a business",
    altLabel: "New hustle",
    activeTenseLabel: "starting my new business",
    icon: "💸",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c53402170b8adfc185",
    label: "Take care of an emergency",
    altLabel: "Emergency plan",
    activeTenseLabel: "taking care of my emergency",
    icon: "🧯",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c63402170b8adfc18f",
    label: "Take care of my family",
    altLabel: "Family finances",
    activeTenseLabel: "taking care of my family",
    icon: "💚",
    requiresCustomLabel: false,
  },
  {
    id: "6426a0c63402170b8adfc199",
    label: "Further my education",
    altLabel: "Education",
    activeTenseLabel: "furthering my education",
    icon: "🎓",
    requiresCustomLabel: false,
  },
  {
    id: "647473c76e1728d3379fb2a8",
    label: "Custom goal",
    altLabel: "custom goal",
    activeTenseLabel: "achieving my custom goal",
    icon: "🎯",
    requiresCustomLabel: true,
  },
];
